### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by esskay09** [acsbendi/Android-Request-Inspector-WebView#1]
failed to set the 'responsetype' property on 'xmlhttprequest': the response type cannot be changed for synchronous requests made from a document.

**Comment by acsbendi** [comment]
Thanks for the report! 

The code in this library is not setting that property, so it's a bit strange. Can you share some code you're using or at least the URL of the website in the WebView?

**Comment by esskay09** [comment]
www.stage.googly.gg

**Comment by esskay09** [comment]
https://stage.googly.gg/home

**Comment by acsbendi** [comment]
Based on that URL, I was able to investigate the cause of the error and [fixed it](https://github.com/acsbendi/Android-Request-Inspector-WebView/commit/4101bb862d22647148d957303e45a8c917374a8d). If you update the latest version of this library (1.0.2), the error should go away.

**Comment by esskay09** [comment]
Thansks! You are a life saver

**Comment by acsbendi** [comment]
You're welcome!
