### ISSUE TITLE
getting recorded request doesn't work

### ISSUE THREAD

**Issue by kumold** [acsbendi/Android-Request-Inspector-WebView#11]
recorded request fetched with condition `url.contains(recordedRequest.url)`, but if `url = "https://somedomain.com/some/paths/here"` and there was a request with url `https://somedomain.com/some/path` it will give wrong request.
Fix might be comparing extensively all recorded requests with all options.

**Comment by acsbendi** [comment]
Yes, that's true. I think we should first check full match (`==`) and then, if no requests are found that way, we should fall back to `contains` since there are cases we can't/don't record the full URL from Javascript. What do you think?

**Comment by alaershov** [comment]
This is an extremly annoying and subtle bug that broke 3ds in my app in a weird way - I got wrong body for a request because of `contains`. A fix would be much appreciated)

**Comment by acsbendi** [comment]
This was fixed by https://github.com/acsbendi/Android-Request-Inspector-WebView/pull/15 and it's available in `1.0.5`. Thanks for the reports!
