### ISSUE TITLE
Hello! I've been using the following code to make calls and noticed that most of the requests made by the WebView are showing up in my console. However, some requests are not appearing in my console. Why is this happening?

### ISSUE THREAD

**Issue by XK14** [acsbendi/Android-Request-Inspector-WebView#14]
Hello! I've been using the following code to make calls and noticed that most of the requests made by the WebView are showing up in my console. However, some requests are not appearing in my console. Why is this happening?
**
RequestInspectorWebViewClient requestInspector = new RequestInspectorWebViewClient(webview);
webview.setWebViewClient(requestInspector);**

**Comment by acsbendi** [comment]
Could you provide the URL of the website you're looking at and which requests are not shown? Without that, I can't tell what could be the issue.

**Comment by acsbendi** [comment]
I'll close this for now since it doesn't describe a concrete issue, feel free to reopen if you have more information.
