### ISSUE TITLE
Crash - Payment - Missing Value filed

### ISSUE THREAD

**Issue by mmfaragallah** [acsbendi/Android-Request-Inspector-WebView#20]
I am getting the following exception even while using the latest version of the library. Could you help me, as this blocks the payment integration.

implementation "com.github.acsbendi:Android-Request-Inspector-WebView:1.0.7"

> W  org.json.JSONException: No value for value
W  	at org.json.JSONObject.get(JSONObject.java:400)
W  	at org.json.JSONObject.getString(JSONObject.java:561)
W  	at com.acsbendi.requestinspectorwebview.RequestInspectorJavaScriptInterface.getUrlEncodedFormBody(RequestInspectorJavaScriptInterface.kt:114)
W  	at com.acsbendi.requestinspectorwebview.RequestInspectorJavaScriptInterface.recordFormSubmission(RequestInspectorJavaScriptInterface.kt:53)
W  	at android.os.MessageQueue.nativePollOnce(Native Method)
W  	at android.os.MessageQueue.next(MessageQueue.java:335)
W  	at android.os.Looper.loop(Looper.java:183)
W  	at android.os.HandlerThread.run(HandlerThread.java:67)
I  [INFO:CONSOLE(29)] "Uncaught Error: Java exception was raised during method invocation", source: https://secureacceptance.cybersource.com/checkout (29)
W  requestCursorAnchorInfo on inactive InputConnection
W  org.json.JSONException: No value for value
W  	at org.json.JSONObject.get(JSONObject.java:400)
W  	at org.json.JSONObject.getString(JSONObject.java:561)
W  	at com.acsbendi.requestinspectorwebview.RequestInspectorJavaScriptInterface.getUrlEncodedFormBody(RequestInspectorJavaScriptInterface.kt:114)
W  	at com.acsbendi.requestinspectorwebview.RequestInspectorJavaScriptInterface.recordFormSubmission(RequestInspectorJavaScriptInterface.kt:53)
W  	at android.os.MessageQueue.nativePollOnce(Native Method)
W  	at android.os.MessageQueue.next(MessageQueue.java:335)
W  	at android.os.Looper.loop(Looper.java:183)
W  	at android.os.HandlerThread.run(HandlerThread.java:67)
I  [INFO:CONSOLE(29)] "Uncaught (in promise) Error: Java exception was raised during method invocation", source: https://secureacceptance.cybersource.com/checkout (29)

**Comment by mmfaragallah** [comment]
@acsbendi, I appreciate your assistance in fixing this issue.

**Comment by acsbendi** [comment]
@mmfaragallah Should be fixed in the latest version, thanks for the report!
