### ISSUE TITLE
Beacon request method without body

### ISSUE THREAD

**Issue by sunleidehao** [acsbendi/Android-Request-Inspector-WebView#22]
Why is it that if a webpage requests an interface using beacon mode and the intercepted request does not have a body? I hope to get your help

**Comment by sunleidehao** [comment]
![Uploading beacon_mode_no_body.png…]()

**Comment by acsbendi** [comment]
I can't see the picture. It would be useful to include the page (URL) as well as the request where you're experiencing this.

**Comment by sunleidehao** [comment]
![beacon_mode_no_body](https://github.com/user-attachments/assets/15f93e69-0621-4aa7-985f-b94433b7196a)

**Comment by acsbendi** [comment]
@sunleidehao Can you provide a reproduction? It's impossible to know what's wrong from just that picture.

**Comment by acsbendi** [comment]
Not reproducible.
