### ISSUE TITLE
Can your library add custom headers to all HTTP or HTTPS requests made by the WebView?

### ISSUE THREAD

**Issue by wanliyunyan** [acsbendi/Android-Request-Inspector-WebView#24]
Can your library add custom headers to all HTTP or HTTPS requests made by the WebView? If it can, please provide a simple example. Thank you! For example, if the WebView sends a POST request, can I intercept it and add custom headers?

**Comment by acsbendi** [comment]
Not currently, but this is very similar to https://github.com/acsbendi/Android-Request-Inspector-WebView/issues/2 and would be a nice feature.
